language: ruby
cache: bundler
rvm:
    - 2.3
    - 2.4
    - 2.5
    - 2.6
script:
    - source .env.test && echo "${GPG_PRIVATE_KEY}" | gpg --import -
    - source .env.test && echo "${GPG_PASSWORD}" | /usr/lib/gnupg/gpg-preset-passphrase --preset "${GPG_FINGERPRINT}"
    - bundle exec rake test
